logs:
  level: debug
  encode: console #json or console
  initFields:
    package: tilestream.v1
    server: tile-stream-server
    version: 0.1.0
  file:
    maxSize: 100
    maxBackups: 10
    maxAge: 28